#!/bin/sh

# Run to start the whole system up, 5 services (one is nginx)
# `./run``
# Or, run with a parameter service name (from docker-compose) to restart just that service
# `./run meminator`

set -x # print what you run
set -e 

docker compose up --build -d $*

HONEYCOMB_API_KEY=$HONEYCOMB_API_KEY_LOCAL_MARKERS ./scripts/create-marker.sh $*

echo "http://localhost:8080"
